#ifndef PINS_H

#define PINS_H

#define FLASH_RESET_N_PORT PORTB
#define FLASH_RESET_N_DDR DDRB
#define FLASH_RESET_N_BIT PB6
#define FLASH_RESET_N_PIN PINB

#define FLASH_CS_N_PORT PORTD
#define FLASH_CS_N_DDR DDRD
#define FLASH_CS_N_BIT PD7
#define FLASH_CS_N_PIN PIND

#define FLASH_SI_PORT PORTB
#define FLASH_SI_DDR DDRB
#define FLASH_SI_BIT PB2
#define FLASH_SI_PIN PINB

#define FLASH_SCK_PORT PORTB
#define FLASH_SCK_DDR DDRB
#define FLASH_SCK_BIT PB1
#define FLASH_SCK_PIN PINB

#define FLASH_SO_PORT PORTB
#define FLASH_SO_DDR DDRB
#define FLASH_SO_BIT PB3
#define FLASH_SO_PIN PINB

#define FPGA_PROGRAM_N_PORT PORTE
#define FPGA_PROGRAM_N_DDR DDRE
#define FPGA_PROGRAM_N_BIT PE2
#define FPGA_PROGRAM_N_PIN PINE

#define FPGA_DONE_PORT PORTE
#define FPGA_DONE_DDR DDRE
#define FPGA_DONE_BIT PE4
#define FPGA_DONE_PIN PINE

#define FPGA_INIT_PORT PORTE
#define FPGA_INIT_DDR DDRE
#define FPGA_INIT_BIT PE5
#define FPGA_INIT_PIN PINE

#define FLASH_WLOCK_N_PORT PORTA
#define FLASH_WLOCK_N_DDR DDRA
#define FLASH_WLOCK_N_BIT PA3
#define FLASH_WLOCK_N_PIN PINA

#endif
